export const FETCH_REQUEST = 'FETCH_REQUEST';
export const UPDATE_REQUEST = 'UPDATE_REQUEST';
export const DELETE_REQUEST = 'DELETE_REQUEST';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';

export const SET_TOKEN = 'SET_TOKEN';

export const GET_TOKEN = 'GET_TOKEN';